### ISSUE TITLE
Does not build on solaris.

### ISSUE THREAD

**Issue by gabyx** [otiai10/copy#68]
Hi.

I receive the following in goreleaser on solaris:

```
⨯ release failed after 186.87s error=failed to build for solaris_amd64: exit status 2: # github.com/otiai10/copy
vendor/github.com/otiai10/copy/copy_namedpipes.go:16:9: undefined: syscall.Mkfifo
vendor/github.com/otiai10/copy/test_setup.go:16:2: undefined: syscall.Mkfifo
```

**Comment by otiai10** [comment]
can you give me "go env"

**Comment by otiai10** [comment]
🤔 https://github.com/otiai10/copy/blob/main/copy_namedpipes.go#L1

**Comment by gabyx** [comment]
Sorry i first update to 1.7.0, then check again.

**Comment by gabyx** [comment]
Was on 1.6.0

**Comment by otiai10** [comment]
Can you provide the output of `go env`?
https://pkg.go.dev/cmd/go#hdr-Print_Go_environment_information

**Comment by gabyx** [comment]
It works on 1.7.0
